#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_keys}

package_update: true
package_upgrade: false

packages:
  - vim
  - nginx

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
